var app = new Vue({
  el:'#app',
  data:{
    columns:[
      {
        title:'姓名',
        key:'name'
      },
      {
        title:'年龄',
        key:'age',
        sortable:true
      },
      {
        title:'出生日期',
        key:'birthday',
        sortable:true
      },
      {
        title:'地址',
        key:'address'
      }
    ],
    data:[
      {
        name:'王小明',
        age:18,
        birthday:'1990-02-21',
        address:'北京市朝阳区芍药居'
      },
      {
        name:'王力宏',
        age:25,
        birthday:'1990-01-23',
        address:'北京市朝阳区芍药居'
      },
      {
        name:'李华',
        age:30,
        birthday:'1980-02-09',
        address:'北京市朝阳区芍药居'
      },
      {
        name:'周伟',
        age:26,
        birthday:'1994-06-25',
        address:'北京市朝阳区芍药居'
      }
    ]
  },
  methods:{
    handleAddData:function(){
      this.data.push({
        name:'张小天',
        age:19,
        birthday:'1998-05-30',
        address:'北京市东城区东直门'
      });
    }
  }
});